"""
Scans data/external/{id}/{id}_ext_var.xlsx and (re)generates config/commodities.yaml
and config/drivers/candidates/{id}.yaml.

Non-destructive by design:
  - A commodity whose commodities.yaml entry already has drivers_status: selected
    is left completely untouched on rerun (no field is regenerated, including
    display_name/grade/region/frequency/start_period/data.file). This is the
    ONLY way a commodity ends up "selected" — it never happens automatically.
  - config/drivers/selected/{id}.yaml existing on disk has NO bearing on
    drivers_status — a pre-existing selected/{id}.yaml is kept only as a
    reference baseline; it does NOT bootstrap drivers_status to "selected."
    Every commodity without an existing "selected" commodities.yaml entry
    starts as "candidates" and goes through feature_selection.py.
  - config/drivers/candidates/{id}.yaml is only written if it does not already
    exist — an existing candidates file is treated as potentially hand-edited
    (per its own header comment) and is never overwritten.
  - Everything without an existing "selected" commodities.yaml entry is
    treated the same way regardless of history: fields are derived
    best-effort from the excel file's header rows, position-based, and
    drivers_status defaults to "candidates".

Header schema is NOT assumed to be identical across commodities (some
files have an extra leading metadata row compared to others) —
header_rows is auto-detected per file, not hardcoded, and display_name/
grade/region derivation degrades gracefully when a cell doesn't look like
what it's expected to be.

Usage: python src/scripts/scaffold_config.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_EXTERNAL = PROJECT_ROOT / "data" / "external"
CONFIG_DIR = PROJECT_ROOT / "config"
COMMODITIES_YAML = CONFIG_DIR / "commodities.yaml"
CANDIDATES_DIR = CONFIG_DIR / "drivers" / "candidates"

COMMODITIES_YAML_HEADER = """\
# AUTO-GENERATED by src/scripts/scaffold_config.py — do not hand-edit
# entries for id/display_name/grade/region/frequency/start_period/data.file,
# they get overwritten on the next scaffold run. `drivers_status` and
# `drivers_config` ARE safe to hand-edit (scaffold won't touch a
# commodity whose drivers_status is already "selected").
#
# horizon_periods is NOT stored here — it's looked up from
# config/horizon_defaults.yaml by `frequency` at runtime, so it never
# needs repeating per commodity.
"""


def detect_header_rows(raw: pd.DataFrame, date_col: int = 0, max_scan: int = 10) -> int:
    """Number of leading rows before the first row whose date_col parses as a date."""
    for i in range(min(max_scan, len(raw))):
        if pd.notna(pd.to_datetime(raw.iat[i, date_col], errors="coerce")):
            return i
    raise ValueError(f"Could not find a date row in the first {max_scan} rows")


def infer_frequency(dates: pd.Series) -> str:
    diffs = dates.sort_values().diff().dropna().dt.days
    if diffs.empty:
        return "unknown"
    median_gap = diffs.median()
    if median_gap <= 45:
        return "monthly"
    if median_gap <= 120:
        return "quarterly"
    return "unknown"


def derive_display_name(commodity_id: str, header: pd.DataFrame) -> str:
    """Prefer the file's own (row 0, col 1) label if it plausibly names the
    commodity (shares a token with commodity_id); otherwise fall back to
    title-casing the id. Handles soybean's extra "Variable Rationale" lead
    row, which pushes the real name out of (row 0, col 1)."""
    fallback = commodity_id.replace("_", " ").title()
    try:
        candidate = str(header.iat[0, 1]).strip()
    except IndexError:
        return fallback
    tokens = commodity_id.split("_")
    if candidate and any(tok.lower() in candidate.lower() for tok in tokens):
        return candidate
    return fallback


_GENERIC_VALUE_DENYLIST = {"price", "value", "index", "exports", "nan", ""}


def derive_grade_region(header: pd.DataFrame, header_rows: int) -> tuple[str | None, str | None]:
    """Position-based: scan header rows 1..header_rows-1, column 0 for a
    label containing "region" or "grade", and take column 1 as its value.
    Rows labeled "unit" or containing a repeated date ("Forecasted Period"
    placeholder rows) are skipped. A candidate value that's a generic
    column-role word (e.g. "Price") rather than an actual grade/region name
    is rejected — this happens on files like soybean's, whose row label is
    "Grade/Index" but whose column-1 value is just "Price" (a data-type
    marker, not the commodity's grade). Either field may come back None —
    that's expected when the file doesn't carry that dimension; fill it in
    by hand once, before the commodity is marked drivers_status: selected,
    since scaffold won't touch it after that."""
    grade, region = None, None
    for r in range(1, header_rows):
        label = str(header.iat[r, 0]).strip().lower()
        value = str(header.iat[r, 1]).strip()
        if value.lower() in _GENERIC_VALUE_DENYLIST:
            continue
        if "region" in label:
            region = value
        elif "grade" in label:
            grade = value
    return grade, region


def derive_candidate_drivers(header: pd.DataFrame, header_rows: int, ncols: int) -> list[dict]:
    """One entry per driver column (Excel-style 1-indexed, matching the
    selected/{id}.yaml convention), label built from whichever header rows
    aren't the unit row or a repeated-date placeholder row."""
    unit_row = None
    for r in range(header_rows):
        if "unit" in str(header.iat[r, 0]).strip().lower():
            unit_row = r
            break

    drivers = []
    for col in range(2, ncols):  # 0-indexed col 2 = 3rd column = first driver
        parts = []
        for r in range(header_rows):
            if r == unit_row:
                continue
            val = str(header.iat[r, col]).strip()
            if not val or val.lower() == "nan":
                continue
            if pd.notna(pd.to_datetime(val, errors="coerce")):
                continue  # skip "Forecasted Period" style repeated-date placeholders
            parts.append(val)
        label = " — ".join(parts) if parts else f"Driver column {col + 1}"
        unit = str(header.iat[unit_row, col]).strip() if unit_row is not None else "TBD"
        drivers.append({"column": col + 1, "label": label, "unit": unit or "TBD"})
    return drivers


def scan_commodity(commodity_id: str, xlsx_path: Path) -> dict:
    sheet_name = pd.ExcelFile(xlsx_path).sheet_names[0]
    raw = pd.read_excel(xlsx_path, sheet_name=0, header=None)
    header_rows = detect_header_rows(raw)
    header = raw.iloc[:header_rows]
    data = raw.iloc[header_rows:]

    dates = pd.to_datetime(data.iloc[:, 0], errors="coerce").dropna()
    start_period = dates.min().strftime("%Y-%m")
    frequency = infer_frequency(dates)

    display_name = derive_display_name(commodity_id, header)
    grade, region = derive_grade_region(header, header_rows)
    candidate_drivers = derive_candidate_drivers(header, header_rows, raw.shape[1])

    return {
        "display_name": display_name,
        "grade": grade,
        "region": region,
        "frequency": frequency,
        "start_period": start_period,
        "header_rows": header_rows,
        "sheet_name": sheet_name,
        "candidate_drivers": candidate_drivers,
    }


def load_existing_commodities() -> dict[str, dict]:
    if not COMMODITIES_YAML.exists():
        return {}
    with open(COMMODITIES_YAML, encoding="utf-8") as fh:
        doc = yaml.safe_load(fh) or {}
    return {c["id"]: c for c in doc.get("commodities", [])}


def write_candidates_yaml(commodity_id: str, rel_data_file: str, scan: dict) -> None:
    path = CANDIDATES_DIR / f"{commodity_id}.yaml"
    if path.exists():
        return  # never overwrite — may be hand-edited, see _template.yaml
    doc_lines = [
        "# AUTO-GENERATED by src/scripts/scaffold_config.py — hand-edit only to",
        "# drop/add a candidate column before feature_selection.py runs. Once",
        "# this file exists, scaffold_config.py will not overwrite it.",
        "#",
        "# Lag: dynamic per driver, not fixed — see",
        "# src/data/external_driver_loader.py.",
        "",
    ]
    body = {
        "commodity_id": commodity_id,
        "data_file": rel_data_file,
        "sheet_name": scan["sheet_name"],
        "header_rows": scan["header_rows"],
        "date_column": 1,
        "price_column": 2,
        "lag_search_range": [1, 3],
        "candidate_drivers": scan["candidate_drivers"],
        "min_sample_size": None,
        "feedstock_margin_spread": {"enabled": False, "feedstock_driver_column": None},
    }
    path.write_text(
        "\n".join(doc_lines) + yaml.dump(body, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    print(f"  wrote {path.relative_to(PROJECT_ROOT)}")


def main() -> None:
    if not DATA_EXTERNAL.is_dir():
        print(f"No data/external/ directory at {DATA_EXTERNAL}", file=sys.stderr)
        sys.exit(1)

    existing = load_existing_commodities()
    entries: list[dict] = []

    for commodity_dir in sorted(DATA_EXTERNAL.iterdir()):
        if not commodity_dir.is_dir():
            continue
        commodity_id = commodity_dir.name
        xlsx_path = commodity_dir / f"{commodity_id}_ext_var.xlsx"
        if not xlsx_path.is_file():
            print(f"  skip {commodity_id}: no {xlsx_path.name} found", file=sys.stderr)
            continue

        prior = existing.get(commodity_id)
        if prior and prior.get("drivers_status") == "selected":
            print(f"  {commodity_id}: drivers_status already selected — left untouched")
            entries.append(prior)
            continue

        rel_data_file = f"data/external/{commodity_id}/{commodity_id}_ext_var.xlsx"
        scan = scan_commodity(commodity_id, xlsx_path)

        if prior:
            drivers_status = prior.get("drivers_status", "candidates")
            drivers_config = prior.get(
                "drivers_config", f"config/drivers/candidates/{commodity_id}.yaml"
            )
            print(f"  {commodity_id}: refreshed derived fields, preserved drivers_status={drivers_status}")
        else:
            drivers_status = "candidates"
            drivers_config = f"config/drivers/candidates/{commodity_id}.yaml"
            print(f"  {commodity_id}: new commodity, drivers_status=candidates")

        # write_candidates_yaml no-ops if the file already exists (may be
        # hand-edited) — safe to call unconditionally whenever a commodity
        # is meant to have a candidates file, whether it's brand new or its
        # candidates file was deleted/never generated.
        if drivers_status == "candidates" and drivers_config == f"config/drivers/candidates/{commodity_id}.yaml":
            write_candidates_yaml(commodity_id, rel_data_file, scan)

        entries.append(
            {
                "id": commodity_id,
                "display_name": scan["display_name"],
                "grade": scan["grade"],
                "region": scan["region"],
                "frequency": scan["frequency"],
                "start_period": scan["start_period"],
                "data": {"file": rel_data_file},
                "drivers_status": drivers_status,
                "drivers_config": drivers_config,
            }
        )

    entries.sort(key=lambda e: e["id"])
    body = yaml.dump({"commodities": entries}, sort_keys=False, allow_unicode=True)
    COMMODITIES_YAML.write_text(COMMODITIES_YAML_HEADER + "\n" + body, encoding="utf-8")
    print(f"\nWrote {COMMODITIES_YAML.relative_to(PROJECT_ROOT)} ({len(entries)} commodities)")


if __name__ == "__main__":
    main()
